queue_documents_for_indexing:
  cron: "00 4 * * *"
  class: "CacheCallback::BaseCallback"
  queue: high
  description: "This job queues all content for indexing in solr"
queue_documents_for_jiujiuai:
  cron: "0,30 9-17 4-6 5 *"
  class: "Jiujiuai"
  queue: high
  description: "This job queues all jiujiuai"
queue_documents_for_jiujiuai_8:
  cron: "30 8 4-6 5 *"
  class: "Jiujiuai"
  queue: high
  description: "This job queues all jiujiuai"
