defaults: &defaults
 count_per_page: 10
 redis_session_store: redis://cache.nbd.cn:6379/13
 redis_cache_store: redis://cache.nbd.cn:6379/12
 redis_page_cache_store: redis://cache.nbd.cn:6379/14
 redis_obj_store: redis://cache.nbd.cn:6379/15
 domain: www.nbd.cn
 host: http://www.nbd.cn
 ntt_host: http://ntt.nbd.cn
 western_host: http://west.nbd.cn
 club_host: http://club.nbd.cn
 old_host: http://old.nbd.com.cn
 session_domain: .nbd.cn
 weibo_host: http://t.nbd.cn
 domain_length: 1
 default_sub_domain: www
 weibo_sub_domain: t
 ntt_sub_domain: ntt
 western_sub_domain: west
 club_sub_domain: club
 asset_host: "http://static.nbd.cn"
 app_env: "preview"
 apple_purchase_secret: "2bc29027447b4d08a42b72b1f4eee214"
 apple_bid: "com.nbd.TouZiBao"
 iphone_app_key: "2cfdbe40c3663ed11a3358fdd1fb3b5a"
 android_app_key: "aa551d8a948ada5ee2a102fbe93574f0"
 apple_product_ids:
  product_0: "com.nbd.TouZiBao.consumable_one_month"
  product_1: "com.nbd.TouZiBao.consumable_three_months"
  product_2: "com.nbd.TouZiBao.consumable_six_months"
  product_3: "com.nbd.TouZiBao.consumable_one_year"
 
development:
 <<: *defaults
 recaptcha_public_key: "6Lcfo9ASAAAAACAD2HG1YvdpaP9KPJDcYRhYQxeU"
 recaptcha_private_key: "6Lcfo9ASAAAAAC34-f6CcXS8nopuogAxS7jtz8N_"
 apple_verify_url: "https://sandbox.itunes.apple.com/verifyReceipt"
 
test:
 <<: *defaults
 
production:
 <<: *defaults
 recaptcha_public_key: "6LdSo9ASAAAAAKyfy_7ZdJWlCHDBab0tI69qJVDV"
 recaptcha_private_key: "6LdSo9ASAAAAAOGIaCo3qK4Kui5T8WEE1f9SBx0z"
 apple_verify_url: "https://buy.itunes.apple.com/verifyReceipt"
