test:
  address: searchd.nbd.cn
  port: 9312  
  bin_path: /opt/coreseek/bin  
  mem_limit: 128M  
  config_file: config/test.sphinx.conf  
  charset_type: zh_cn.utf-8  
  charset_dictpath: <%=::Rails.root.to_s + "/fulltext_search_data "%>  
  pid_file: "/tmp/searchd.test.pid"  
  ngram_len: 0  
  
development:
  indexed_models:
    - User
    - Weibo
    - Article
    - Image
  address: searchd.nbd.cn
  port: 9312
  bin_path: /opt/coreseek/bin  
  mem_limit: 128M  
  config_file: config/development.sphinx.conf  
  charset_type: zh_cn.utf-8  
  charset_dictpath: /shared/fulltext_search_data
  pid_file: "/tmp/searchd.development.pid"
  searchd_file_path: /shared/db/sphinx/development
  ngram_len: 0  
  
production:
  indexed_models:
    - User
    - Weibo
    - Article
    - Image
  address: searchd.nbd.cn
  port: 9312  
  bin_path: /usr/local/bin
  mem_limit: 128M  
  config_file: config/production.sphinx.conf  
  charset_type: zh_cn.utf-8  
  charset_dictpath: /shared/fulltext_search_data
  pid_file: "/tmp/searchd.production.pid"
  searchd_file_path: /shared/db/sphinx/production
  ngram_len: 0