require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StockLivesController do

  def mock_stock_live(stubs={})
    @mock_stock_live ||= mock_model(StockLive, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all stock_lives as @stock_lives" do
      StockLive.stub(:all) { [mock_stock_live] }
      get :index
      assigns(:stock_lives).should eq([mock_stock_live])
    end
  end

  describe "GET show" do
    it "assigns the requested stock_live as @stock_live" do
      StockLive.stub(:find).with("37") { mock_stock_live }
      get :show, :id => "37"
      assigns(:stock_live).should be(mock_stock_live)
    end
  end

  describe "GET new" do
    it "assigns a new stock_live as @stock_live" do
      StockLive.stub(:new) { mock_stock_live }
      get :new
      assigns(:stock_live).should be(mock_stock_live)
    end
  end

  describe "GET edit" do
    it "assigns the requested stock_live as @stock_live" do
      StockLive.stub(:find).with("37") { mock_stock_live }
      get :edit, :id => "37"
      assigns(:stock_live).should be(mock_stock_live)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created stock_live as @stock_live" do
        StockLive.stub(:new).with({'these' => 'params'}) { mock_stock_live(:save => true) }
        post :create, :stock_live => {'these' => 'params'}
        assigns(:stock_live).should be(mock_stock_live)
      end

      it "redirects to the created stock_live" do
        StockLive.stub(:new) { mock_stock_live(:save => true) }
        post :create, :stock_live => {}
        response.should redirect_to(stock_life_url(mock_stock_live))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stock_live as @stock_live" do
        StockLive.stub(:new).with({'these' => 'params'}) { mock_stock_live(:save => false) }
        post :create, :stock_live => {'these' => 'params'}
        assigns(:stock_live).should be(mock_stock_live)
      end

      it "re-renders the 'new' template" do
        StockLive.stub(:new) { mock_stock_live(:save => false) }
        post :create, :stock_live => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stock_live" do
        StockLive.stub(:find).with("37") { mock_stock_live }
        mock_stock_life.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :stock_live => {'these' => 'params'}
      end

      it "assigns the requested stock_live as @stock_live" do
        StockLive.stub(:find) { mock_stock_live(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:stock_live).should be(mock_stock_live)
      end

      it "redirects to the stock_live" do
        StockLive.stub(:find) { mock_stock_live(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(stock_life_url(mock_stock_live))
      end
    end

    describe "with invalid params" do
      it "assigns the stock_live as @stock_live" do
        StockLive.stub(:find) { mock_stock_live(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:stock_live).should be(mock_stock_live)
      end

      it "re-renders the 'edit' template" do
        StockLive.stub(:find) { mock_stock_live(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stock_live" do
      StockLive.stub(:find).with("37") { mock_stock_live }
      mock_stock_life.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the stock_lives list" do
      StockLive.stub(:find) { mock_stock_live }
      delete :destroy, :id => "1"
      response.should redirect_to(stock_lives_url)
    end
  end

end
