development:
  adapter: mysql2
  database: nbd
  port: 3306
  host: db.nbd.cn
  username: 'nbddog'
  password: 'nbd5290cd'

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet

production:
  adapter: mysql2
  database: nbd
  port: 3306
  host: db.nbd.cn
  username: 'nbddog'
  password: 'nbd5290cd'

nbdcms:
  adapter: mysql2
  database: nbdcms
  port: 3306
  host: 125.64.23.145
  username: 'nbdadmin'
  password: '65092nbd'
